title: Siddhant Tandon # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Hi there! I am a M.S.E candidate in Aerospace Engineering at the University of Michigan. My interests lie in controls, autonomous systems and uncertainty quantification.
  <br><br>
  I graduated from Purdue University with a B.S. in Aeronautics and Astronautics, 2019.  
  <br><br>
  <a href="https://www.linkedin.com/in/siddhant-tandon/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
#google_analytics: UA-000000-0 # your Google Analytics tracking ID here
